from datagrunt.core import (
    CSVColumnNameNormalizer,
    CSVColumns,
    CSVComponents,
    CSVDelimiter,
    CSVDialect,
    CSVRows,
    CSVStringSample,
)
from datagrunt.core.csv_io.csvcomponents import _is_legacy_mac_newlines


class TestLegacyMacNewlineProbe:
    """_is_legacy_mac_newlines narrows to OSError (issue #151).

    The probe is a best-effort binary read; an unreadable file must still fall
    back to ``False`` (not legacy-mac), while any non-OSError is now a real bug
    that propagates instead of being silently swallowed.
    """

    def test_missing_file_returns_false(self, tmp_path):
        """A missing/unreadable path is caught as OSError and yields False."""
        assert _is_legacy_mac_newlines(tmp_path / "does_not_exist.csv") is False

    def test_legacy_mac_file_detected(self, tmp_path):
        """A genuine \\r-only file is still detected as legacy-mac."""
        mac_file = tmp_path / "legacy.csv"
        mac_file.write_bytes(b"a,b,c\r1,2,3\r4,5,6")
        assert _is_legacy_mac_newlines(mac_file) is True

    def test_unix_file_not_detected(self, tmp_path):
        """A normal \\n file is not legacy-mac."""
        unix_file = tmp_path / "unix.csv"
        unix_file.write_bytes(b"a,b,c\n1,2,3\n")
        assert _is_legacy_mac_newlines(unix_file) is False


class TestCSVStringSample:
    """Test suite for the CSVStringSample class."""

    def test_csv_string_sample_by_quality(self, tmp_path):
        # Create a temporary CSV file with mixed quality rows
        test_file = tmp_path / "quality_test.csv"
        test_file.write_text("a,b,c\n1,2,3\n1,,\n4,5,6\n,,")

        # Get the quality sample
        sampler = CSVStringSample(str(test_file))
        quality_sample = sampler.csv_string_sample_by_quality

        # The top two rows should be the ones with no nulls
        assert "1,2,3" in quality_sample
        assert "4,5,6" in quality_sample
        assert "1,," not in quality_sample

    def test_csv_string_sample(self, tmp_path):
        # Create a temporary CSV file
        test_file = tmp_path / "sample_test.csv"
        test_file.write_text("a,b,c\n1,2,3\n4,5,6\n7,8,9")

        # Get the sample
        sampler = CSVStringSample(str(test_file))
        sample = sampler.csv_string_sample

        # The sample should contain the header and the first two rows
        assert "a,b,c" in sample
        assert "1,2,3" in sample
        assert "4,5,6" in sample
        assert "7,8,9" not in sample

    def test_csv_string_sample_with_leading_comments(self, tmp_path):
        # Leading '#' comment rows must not crash sampling.
        test_file = tmp_path / "commented_sample.csv"
        test_file.write_text("# generated by exporter\n# version 2\na,b,c\n1,2,3\n4,5,6")

        sampler = CSVStringSample(str(test_file))
        sample = sampler.csv_string_sample

        assert "a,b,c" in sample
        assert "1,2,3" in sample

    def test_csv_string_sample_by_quality_with_leading_comments(self, tmp_path):
        # Leading '#' comment rows must not crash quality sampling.
        test_file = tmp_path / "commented_quality.csv"
        test_file.write_text("# generated by exporter\n# version 2\na,b,c\n1,2,3\n1,,\n4,5,6\n,,")

        sampler = CSVStringSample(str(test_file))
        quality_sample = sampler.csv_string_sample_by_quality

        assert "1,2,3" in quality_sample
        assert "4,5,6" in quality_sample
        assert "1,," not in quality_sample

    def test_csv_string_sample_by_quality_preserves_user_null_count_column(self, tmp_path):
        # A real user column named 'null_count' must survive intact.
        test_file = tmp_path / "user_null_count.csv"
        test_file.write_text("id,null_count\n1,7\n2,42\n3,99")

        sampler = CSVStringSample(str(test_file))
        quality_sample = sampler.csv_string_sample_by_quality

        assert "null_count" in quality_sample
        assert "7" in quality_sample
        assert "42" in quality_sample

    def test_csv_string_sample_retains_hash_leading_data_rows(self, tmp_path):
        # Issue #217: csv_string_sample must NOT drop data rows whose first field
        # starts with '#' (e.g. hex colours). Only the leading comment block should
        # be skipped; '#'-prefixed data rows must be preserved.
        test_file = tmp_path / "hash_data.csv"
        test_file.write_text(
            "# this is a comment\n"
            "# another comment\n"
            "color,name\n"
            "#FF0000,red\n"
            "#00FF00,green\n"
        )

        sampler = CSVStringSample(str(test_file))
        sample = sampler.csv_string_sample

        assert "color,name" in sample, "header must be present"
        assert "#FF0000" in sample, "hex-colour data row must NOT be dropped (issue #217)"
        assert "#00FF00" in sample, "second hex-colour data row must NOT be dropped"

    def test_csv_string_sample_by_quality_retains_hash_leading_data_rows(self, tmp_path):
        # Issue #217: csv_string_sample_by_quality must also keep '#'-prefixed data rows.
        test_file = tmp_path / "hash_data_quality.csv"
        test_file.write_text(
            "# generated by exporter\n"
            "color,name\n"
            "#FF0000,red\n"
            "#00FF00,green\n"
            "#0000FF,blue\n"
        )

        sampler = CSVStringSample(str(test_file))
        quality_sample = sampler.csv_string_sample_by_quality

        assert "color,name" in quality_sample, "header must be present"
        assert "#FF0000" in quality_sample, "hex-colour data row must NOT be dropped (issue #217)"
        assert "#00FF00" in quality_sample, "second hex-colour data row must NOT be dropped"


class TestCSVDelimiter:
    """Test suite for CSVDelimiter class."""

    def test_comma_delimiter(self, sample_csv_files):
        delimiter = CSVDelimiter(sample_csv_files["comma.csv"])
        assert delimiter.delimiter == ","

    def test_tab_delimiter(self, tmp_path):
        # Create a TSV file
        tsv_file = tmp_path / "test.tsv"
        tsv_file.write_text("a\tb\tc\n1\t2\t3")

        delimiter = CSVDelimiter(str(tsv_file))
        assert delimiter.delimiter == "\t"

    def test_semicolon_delimiter(self, tmp_path):
        # Create a semicolon-delimited file
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("a;b;c\n1;2;3")

        delimiter = CSVDelimiter(str(csv_file))
        assert delimiter.delimiter == ";"

    def test_pipe_delimiter(self, tmp_path):
        # Create a pipe-delimited file
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("a|b|c\n1|2|3")

        delimiter = CSVDelimiter(str(csv_file))
        assert delimiter.delimiter == "|"

    def test_single_column_no_whitespace_uses_comma(self, tmp_path):
        """A single-column file with no punctuation must default to comma.

        Counting non-alphanumeric characters finds nothing here, so the old
        code fell back to space; comma never splits single-column data.
        """
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("abc123\ndef456")

        delimiter = CSVDelimiter(str(csv_file))
        assert delimiter.delimiter == ","

    def test_dotted_header_not_treated_as_delimiter(self, tmp_path):
        """A dotted header (user.id,user.name) must infer comma, not '.'."""
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("user.id,user.name\n1,alice\n2,bob")

        delimiter = CSVDelimiter(str(csv_file))
        assert delimiter.delimiter == ","

    def test_apostrophe_header_not_treated_as_delimiter(self, tmp_path):
        """An apostrophe in a header (User's Name,Age) must infer comma, not '."""
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("User's Name,Age\nJohn,30\nJane,25")

        delimiter = CSVDelimiter(str(csv_file))
        assert delimiter.delimiter == ","

    def test_single_column_with_spaces_in_values_not_split(self, tmp_path):
        """A single text column whose values contain spaces must not split.

        Every row splits into two whitespace tokens, but two-token rows are
        indistinguishable from one text column, so the file defaults to comma.
        """
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("full name\nJohn Smith\nJane Doe")

        delimiter = CSVDelimiter(str(csv_file))
        assert delimiter.delimiter == ","

    def test_genuine_space_delimited_file_detected(self, tmp_path):
        """A real space-delimited file (consistent 3+ fields) infers space."""
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("a b c\n1 2 3\n4 5 6")

        delimiter = CSVDelimiter(str(csv_file))
        assert delimiter.delimiter == " "

    def test_consistent_ambiguous_char_detected_as_delimiter(self, tmp_path):
        """A file that splits consistently on '.' is detected as '.'-delimited.

        Multi-pass validation accepts an otherwise-ambiguous character when
        every sampled row splits on it into the same 3+ field count.
        """
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("a.b.c\n1.2.3\n4.5.6")

        delimiter = CSVDelimiter(str(csv_file))
        assert delimiter.delimiter == "."

    def test_dotted_header_falls_through_to_real_delimiter(self, tmp_path):
        """A dotted header over semicolon data infers ';', not the dot or comma.

        '.' is the most frequent header character but splits the data
        inconsistently, so inference falls through to the semicolon rather than
        defaulting to comma.
        """
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("user.id;user.name\n1;alice\n2;bob")

        delimiter = CSVDelimiter(str(csv_file))
        assert delimiter.delimiter == ";"

    def test_safe_delimiter_preferred_over_consistent_punctuation(self, tmp_path):
        """A real comma wins over a more frequent, consistently-splitting dot.

        Dotted values on both sides of a comma (a.b,c.d) make '.' the most
        frequent character and it splits every row consistently, but the comma
        is the actual delimiter and must win.
        """
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("a.b,c.d\n1.2,3.4\n5.6,7.8")

        delimiter = CSVDelimiter(str(csv_file))
        assert delimiter.delimiter == ","

    def test_tab_delimited_with_csv_extension_detected(self, tmp_path):
        """A tab-delimited file mislabeled .csv still infers tab."""
        csv_file = tmp_path / "mislabeled.csv"
        csv_file.write_text("a\tb\tc\n1\t2\t3\n4\t5\t6")

        delimiter = CSVDelimiter(str(csv_file))
        assert delimiter.delimiter == "\t"

    def test_empty_file_uses_comma(self, tmp_path):
        """An empty file defaults to comma without sampling rows."""
        csv_file = tmp_path / "empty.csv"
        csv_file.write_text("")

        delimiter = CSVDelimiter(str(csv_file))
        assert delimiter.delimiter == ","


class TestCSVColumns:
    """Test suite for CSVColumns class."""

    def test_columns_extraction(self, tmp_path):
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("Name,Age,City\nJohn,25,NYC")

        columns = CSVColumns(str(csv_file))
        assert columns.columns == ["Name", "Age", "City"]
        assert columns.columns_count == 3

    def test_columns_string_representation(self, tmp_path):
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("A,B,C\n1,2,3")

        columns = CSVColumns(str(csv_file))
        assert columns.columns_string == "A, B, C"

    def test_empty_file_columns(self, tmp_path):
        csv_file = tmp_path / "empty.csv"
        csv_file.write_text("")

        columns = CSVColumns(str(csv_file))
        assert columns.columns == []
        assert columns.columns_count == 0


class TestCSVColumnNameNormalizer:
    """Test suite for CSVColumnNameNormalizer class."""

    def test_normalize_special_characters(self, tmp_path):
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("First Name,E-mail Address,Phone#\nJohn,john@test.com,123")

        normalizer = CSVColumnNameNormalizer(str(csv_file))
        expected = ["first_name", "e_mail_address", "phone"]
        assert normalizer.columns_normalized == expected

    def test_normalize_leading_digits(self, tmp_path):
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("1st_column,2nd_column,normal_column\na,b,c")

        normalizer = CSVColumnNameNormalizer(str(csv_file))
        expected = ["_1st_column", "_2nd_column", "normal_column"]
        assert normalizer.columns_normalized == expected

    def test_normalize_duplicate_names(self, tmp_path):
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("name,name,Name\na,b,c")

        normalizer = CSVColumnNameNormalizer(str(csv_file))
        # The normalizer should create unique names for duplicates
        normalized = normalizer.columns_normalized
        assert len(normalized) == 3
        assert len(set(normalized)) == 3  # All names should be unique
        assert all("name" in col for col in normalized)  # All should contain "name"

    def test_columns_to_normalized_mapping(self, tmp_path):
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("First Name,Last Name\nJohn,Doe")

        normalizer = CSVColumnNameNormalizer(str(csv_file))
        mapping = normalizer.columns_to_normalized_mapping
        assert mapping["First Name"] == "first_name"
        assert mapping["Last Name"] == "last_name"

    def test_normalized_name_collides_with_existing_suffixed_name(self, tmp_path):
        """The uniquifier must not emit a name that collides with a real column.

        ``Col A`` and ``col a`` both normalize to ``col_a``; the third header
        ``col_a_1`` already occupies the naive ``col_a_1`` suffix. The result
        must be three DISTINCT names, so the suffix counter has to keep
        incrementing past names already taken.
        """
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("Col A,col a,col_a_1\n1,2,3")

        normalizer = CSVColumnNameNormalizer(str(csv_file))
        normalized = normalizer.columns_normalized
        assert len(normalized) == 3
        assert len(set(normalized)) == 3  # no collisions

    def test_header_that_normalizes_to_empty_gets_placeholder(self, tmp_path):
        """A header cell of only special chars must not normalize to ``""``.

        An empty identifier (e.g. from a header of ``%``) is an invalid,
        zero-length SQL identifier. The normalizer must return a non-empty
        placeholder so it can be uniquified into a valid column name.
        """
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("%,name\n1,2")

        normalizer = CSVColumnNameNormalizer(str(csv_file))
        normalized = normalizer.columns_normalized
        assert all(name != "" for name in normalized)
        assert len(set(normalized)) == len(normalized)

    def test_multiple_empty_headers_get_unique_placeholders(self, tmp_path):
        """Several empty-normalizing headers must yield distinct placeholders."""
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("%,(),name\n1,2,3")

        normalizer = CSVColumnNameNormalizer(str(csv_file))
        normalized = normalizer.columns_normalized
        assert all(name != "" for name in normalized)
        assert len(set(normalized)) == 3


class TestCSVRows:
    """Test suite for CSVRows class."""

    def test_row_count_with_header(self, tmp_path):
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("a,b,c\n1,2,3\n4,5,6\n7,8,9")

        rows = CSVRows(str(csv_file))
        assert rows.row_count_with_header == 4

    def test_row_count_without_header(self, tmp_path):
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("a,b,c\n1,2,3\n4,5,6")

        rows = CSVRows(str(csv_file))
        assert rows.row_count_without_header == 2

    def test_row_count_with_header_large_file(self, tmp_path):
        """Streaming row count must handle many records without loading the whole file."""
        csv_file = tmp_path / "large.csv"
        row_total = 50_000
        with open(csv_file, "w", encoding="utf-8") as f:
            f.write("id,value\n")
            for i in range(row_total):
                f.write(f"{i},{i}\n")

        rows = CSVRows(str(csv_file))
        assert rows.row_count_with_header == row_total + 1
        assert rows.row_count_without_header == row_total

    def test_first_row_extraction(self, tmp_path):
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("Name,Age,City\nJohn,25,NYC")

        rows = CSVRows(str(csv_file))
        assert rows.first_row == "Name,Age,City"

    def test_row_count_with_quoted_embedded_newlines(self, tmp_path):
        # A quoted field containing an embedded newline is one CSV record,
        # not two physical lines. Row counts must match what the engines parse.
        csv_file = tmp_path / "embedded_newlines.csv"
        csv_file.write_text('name,notes\nalice,"line1\nline2"\nbob,"hello"\n')

        rows = CSVRows(str(csv_file))
        # header + 2 data records, despite 4 physical lines
        assert rows.row_count_with_header == 3
        assert rows.row_count_without_header == 2

    def test_row_count_excludes_comment_and_blank_records(self, tmp_path):
        csv_file = tmp_path / "comments_blanks.csv"
        csv_file.write_text("# leading comment\n\nname,notes\nalice,1\n\nbob,2\n")

        rows = CSVRows(str(csv_file))
        # header + 2 data records; comment and blank lines excluded
        assert rows.row_count_with_header == 3
        assert rows.row_count_without_header == 2


class TestCSVDialect:
    """Test suite for CSVDialect class."""

    def test_quote_character_detection(self, tmp_path):
        csv_file = tmp_path / "test.csv"
        csv_file.write_text('"Name","Age"\n"John Doe","25"')

        dialect = CSVDialect(str(csv_file))
        assert dialect.quotechar == '"'

    def test_newline_delimiter_detection(self, tmp_path):
        csv_file = tmp_path / "test.csv"
        csv_file.write_text("a,b,c\n1,2,3")

        dialect = CSVDialect(str(csv_file))
        assert dialect.newline_delimiter in ["\r\n", "\n"]

    def test_empty_file_dialect_handling(self, tmp_path):
        csv_file = tmp_path / "empty.csv"
        csv_file.write_text("")

        dialect = CSVDialect(str(csv_file))
        assert dialect.quotechar == '"'  # Default fallback
        assert dialect.escapechar is None
        assert dialect.doublequote is False  # Default when dialect is None
        assert dialect.skipinitialspace is False  # Default when dialect is None
        assert dialect.quoting == "quote minimal"  # Default when dialect is None

    def test_dialect_properties_with_valid_csv(self, tmp_path):
        """Test all dialect properties with a properly formatted CSV."""
        csv_file = tmp_path / "valid.csv"
        csv_file.write_text('"Name","Age"\n"John",25\n"Jane",30')

        dialect = CSVDialect(str(csv_file))
        # Test all properties are accessible
        assert dialect.quotechar == '"'
        assert isinstance(dialect.doublequote, bool)
        assert isinstance(dialect.skipinitialspace, bool)
        assert dialect.quoting in ["no quoting", "quote all", "quote minimal", "quote non-numeric"]
        assert dialect.newline_delimiter in ["\r\n", "\n", "\r"]


class TestCSVComponents:
    """Test suite for CSVComponents integrated class."""

    def test_integrated_components(self, tmp_path):
        csv_file = tmp_path / "test.csv"
        csv_file.write_text('"First Name","Age Group"\n"John Doe","25-30"')

        components = CSVComponents(str(csv_file))

        # Test delimiter detection
        assert components.delimiter == ","

        # Test column extraction
        assert "First Name" in components.columns
        assert "Age Group" in components.columns

        # Test normalization
        assert "first_name" in components.columns_normalized
        assert "age_group" in components.columns_normalized

        # Test row counting
        assert components.row_count_with_header == 2
        assert components.row_count_without_header == 1

        # Test string samples
        assert "First Name" in components.csv_string_sample
        assert "John Doe" in components.csv_string_sample

    def test_components_with_complex_data(self, tmp_path):
        csv_file = tmp_path / "complex.csv"
        csv_file.write_text('ID,Amount,Description\n001,1000.50,"Product A"\n002,0500,"Product B"')

        components = CSVComponents(str(csv_file))

        # Test that the sample contains the expected data structure
        sample = components.csv_string_sample
        assert "ID" in sample
        assert "Amount" in sample
        assert "Description" in sample

        # Test column mapping
        mapping = components.columns_to_normalized_mapping
        assert mapping["ID"] == "id"
        assert mapping["Amount"] == "amount"
        assert mapping["Description"] == "description"

    def test_semicolon_delimiter(self, sample_csv_files):
        delimiter = CSVDelimiter(sample_csv_files["semicolon.csv"])
        assert delimiter.delimiter == ";"

    def test_tab_delimiter(self, sample_csv_files):
        delimiter = CSVDelimiter(sample_csv_files["tab.csv"])
        assert delimiter.delimiter == "\t"

    def test_empty_file_delimiter(self, sample_csv_files):
        delimiter = CSVDelimiter(sample_csv_files["empty.csv"])
        assert delimiter.delimiter == ","  # Should return default delimiter
