name: Publish to PyPI

on:
  workflow_run:
    workflows: ["Bump Version"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      # Checkout the full history to find all tags
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      # Checkout the specific tagged version to publish
      - name: Checkout tagged version
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get_tag.outputs.tag }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: python -m pip install --upgrade build

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1